--------------------------------------------------------
--  File created - Monday-August-01-2022   
--------------------------------------------------------
DROP TABLE "NASRA"."AUTHOR";
DROP TABLE "NASRA"."BOOK";
DROP TABLE "NASRA"."TEMP_EMP";
DROP TABLE "NASRA"."PUBLISHER";
DROP TABLE "NASRA"."PAYMENT";
DROP TABLE "NASRA"."ORDERR";
DROP TABLE "NASRA"."LOGIN";
DROP TABLE "NASRA"."EMPLOYEE";
DROP TABLE "NASRA"."DEPT";
DROP TABLE "NASRA"."CUSTOMER";
DROP TABLE "NASRA"."CATEGORY";
DROP TABLE "NASRA"."BOOK_ORDER";
DROP TABLE "NASRA"."AUTHOR";
DROP TABLE "NASRA"."PUBLISHER";
DROP TABLE "NASRA"."CUSTOMER";
DROP TABLE "NASRA"."EMPLOYEE";
DROP TABLE "NASRA"."BOOK";
DROP TABLE "NASRA"."ORDERR";
DROP TABLE "NASRA"."PAYMENT";
DROP TABLE "NASRA"."CATEGORY";
DROP TABLE "NASRA"."BOOK_ORDER";
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

  CREATE TABLE "NASRA"."AUTHOR" 
   (	"AUTHID" NUMBER(4,0), 
	"AUTHNAME" VARCHAR2(20 BYTE), 
	"AUTHADDRESS" VARCHAR2(20 BYTE), 
	"AUTHPHONE" NUMBER(12,0), 
	"AUTHEMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "NASRA"."BOOK" 
   (	"BOOKID" NUMBER(4,0), 
	"BOOKTITLE" VARCHAR2(20 BYTE), 
	"BOOKVERSION" NUMBER(2,0), 
	"BOOKYEAR" DATE, 
	"BOOKPRICE" NUMBER(2,0), 
	"AUTHID" NUMBER(4,0), 
	"PUBID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEMP_EMP
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "NASRA"."TEMP_EMP" 
   (	"EMPNO" NUMBER, 
	"ENAME" VARCHAR2(10 BYTE)
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------

  CREATE TABLE "NASRA"."PUBLISHER" 
   (	"PUBID" NUMBER(4,0), 
	"PUBNAME" VARCHAR2(20 BYTE), 
	"PUBADDRESS" VARCHAR2(20 BYTE), 
	"PUBPHONE" NUMBER(12,0), 
	"PUBEMIAL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "NASRA"."PAYMENT" 
   (	"PRICE" NUMBER(2,0), 
	"CUSTID" NUMBER(4,0), 
	"EMPID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERR
--------------------------------------------------------

  CREATE TABLE "NASRA"."ORDERR" 
   (	"ORDERID" NUMBER(4,0), 
	"CUSTID" NUMBER(4,0), 
	"EMPID" NUMBER(4,0), 
	"ORDERITEMS" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "NASRA"."LOGIN" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "NASRA"."EMPLOYEE" 
   (	"EMPID" NUMBER(4,0), 
	"EMPNAME" VARCHAR2(20 BYTE), 
	"EMPADDRESS" VARCHAR2(20 BYTE), 
	"EMPPHONE" NUMBER(12,0), 
	"EMPEMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "NASRA"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "NASRA"."CUSTOMER" 
   (	"CUSTID" NUMBER(4,0), 
	"CUSTNAME" VARCHAR2(20 BYTE), 
	"CUSTADDRESS" VARCHAR2(20 BYTE), 
	"CUSTPHONE" NUMBER(12,0), 
	"CUSTEMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "NASRA"."CATEGORY" 
   (	"CATID" NUMBER(4,0), 
	"CATNAME" VARCHAR2(20 BYTE), 
	"CATVERSION" NUMBER(3,0), 
	"BOOKID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK_ORDER
--------------------------------------------------------

  CREATE TABLE "NASRA"."BOOK_ORDER" 
   (	"BOOKORDERID" NUMBER(4,0), 
	"ORDERID" NUMBER(4,0), 
	"BOOKID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------

  CREATE TABLE "NASRA"."AUTHOR" 
   (	"AUTHID" NUMBER(4,0), 
	"AUTHNAME" VARCHAR2(20 BYTE), 
	"AUTHADDRESS" VARCHAR2(20 BYTE), 
	"AUTHPHONE" NUMBER(12,0), 
	"AUTHEMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------

  CREATE TABLE "NASRA"."PUBLISHER" 
   (	"PUBID" NUMBER(4,0), 
	"PUBNAME" VARCHAR2(20 BYTE), 
	"PUBADDRESS" VARCHAR2(20 BYTE), 
	"PUBPHONE" NUMBER(12,0), 
	"PUBEMIAL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "NASRA"."CUSTOMER" 
   (	"CUSTID" NUMBER(4,0), 
	"CUSTNAME" VARCHAR2(20 BYTE), 
	"CUSTADDRESS" VARCHAR2(20 BYTE), 
	"CUSTPHONE" NUMBER(12,0), 
	"CUSTEMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "NASRA"."EMPLOYEE" 
   (	"EMPID" NUMBER(4,0), 
	"EMPNAME" VARCHAR2(20 BYTE), 
	"EMPADDRESS" VARCHAR2(20 BYTE), 
	"EMPPHONE" NUMBER(12,0), 
	"EMPEMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "NASRA"."BOOK" 
   (	"BOOKID" NUMBER(4,0), 
	"BOOKTITLE" VARCHAR2(20 BYTE), 
	"BOOKVERSION" NUMBER(2,0), 
	"BOOKYEAR" DATE, 
	"BOOKPRICE" NUMBER(2,0), 
	"AUTHID" NUMBER(4,0), 
	"PUBID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDERR
--------------------------------------------------------

  CREATE TABLE "NASRA"."ORDERR" 
   (	"ORDERID" NUMBER(4,0), 
	"CUSTID" NUMBER(4,0), 
	"EMPID" NUMBER(4,0), 
	"ORDERITEMS" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "NASRA"."PAYMENT" 
   (	"PRICE" NUMBER(2,0), 
	"CUSTID" NUMBER(4,0), 
	"EMPID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "NASRA"."CATEGORY" 
   (	"CATID" NUMBER(4,0), 
	"CATNAME" VARCHAR2(20 BYTE), 
	"CATVERSION" NUMBER(3,0), 
	"BOOKID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK_ORDER
--------------------------------------------------------

  CREATE TABLE "NASRA"."BOOK_ORDER" 
   (	"BOOKORDERID" NUMBER(4,0), 
	"ORDERID" NUMBER(4,0), 
	"BOOKID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NASRA.AUTHOR
SET DEFINE OFF;
Insert into NASRA.AUTHOR (AUTHID,AUTHNAME,AUTHADDRESS,AUTHPHONE,AUTHEMAIL) values (1,'J. K. Rowling','USA',104290942,'KJROWLING@gmail.com');
Insert into NASRA.AUTHOR (AUTHID,AUTHNAME,AUTHADDRESS,AUTHPHONE,AUTHEMAIL) values (2,'nasra','barubax',329090,'dsfkdsk');
Insert into NASRA.AUTHOR (AUTHID,AUTHNAME,AUTHADDRESS,AUTHPHONE,AUTHEMAIL) values (3,'iqra','lsddfl',204230,'dskfdsk');
Insert into NASRA.AUTHOR (AUTHID,AUTHNAME,AUTHADDRESS,AUTHPHONE,AUTHEMAIL) values (6,'abayo','dfkjdk',395830,'jdkfk');
REM INSERTING into NASRA.BOOK
SET DEFINE OFF;
Insert into NASRA.BOOK (BOOKID,BOOKTITLE,BOOKVERSION,BOOKYEAR,BOOKPRICE,AUTHID,PUBID) values (1,'fffvfd',2,to_date('03-JUN-20','DD-MON-RR'),5,1,1);
REM INSERTING into NASRA.TEMP_EMP
SET DEFINE OFF;
REM INSERTING into NASRA.PUBLISHER
SET DEFINE OFF;
Insert into NASRA.PUBLISHER (PUBID,PUBNAME,PUBADDRESS,PUBPHONE,PUBEMIAL) values (1,'maxamed cabdi','jigjigo',3209890,'lkdflkgslk');
REM INSERTING into NASRA.PAYMENT
SET DEFINE OFF;
REM INSERTING into NASRA.ORDERR
SET DEFINE OFF;
Insert into NASRA.ORDERR (ORDERID,CUSTID,EMPID,ORDERITEMS) values (1,1,1,1);
REM INSERTING into NASRA.LOGIN
SET DEFINE OFF;
REM INSERTING into NASRA.EMPLOYEE
SET DEFINE OFF;
Insert into NASRA.EMPLOYEE (EMPID,EMPNAME,EMPADDRESS,EMPPHONE,EMPEMAIL) values (1,'nasra',null,null,null);
REM INSERTING into NASRA.DEPT
SET DEFINE OFF;
REM INSERTING into NASRA.CUSTOMER
SET DEFINE OFF;
Insert into NASRA.CUSTOMER (CUSTID,CUSTNAME,CUSTADDRESS,CUSTPHONE,CUSTEMAIL) values (1,'iqra',null,null,null);
REM INSERTING into NASRA.CATEGORY
SET DEFINE OFF;
REM INSERTING into NASRA.BOOK_ORDER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AUTHOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."AUTHOR_PK" ON "NASRA"."AUTHOR" ("AUTHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."BOOK_PK" ON "NASRA"."BOOK" ("BOOKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PUBLISHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."PUBLISHER_PK" ON "NASRA"."PUBLISHER" ("PUBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."PAYMENT_PK" ON "NASRA"."PAYMENT" ("PRICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDERR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."ORDERR_PK" ON "NASRA"."ORDERR" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."EMPLOYEE_PK" ON "NASRA"."EMPLOYEE" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."CUSTOMER_PK" ON "NASRA"."CUSTOMER" ("CUSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."CATEGORY_PK" ON "NASRA"."CATEGORY" ("CATID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOOK_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASRA"."BOOK_ORDER_PK" ON "NASRA"."BOOK_ORDER" ("BOOKORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AUTHOR
--------------------------------------------------------

  ALTER TABLE "NASRA"."AUTHOR" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("AUTHID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."AUTHOR" MODIFY ("AUTHNAME" NOT NULL ENABLE);
  ALTER TABLE "NASRA"."AUTHOR" MODIFY ("AUTHID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "NASRA"."BOOK" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."BOOK" MODIFY ("BOOKTITLE" NOT NULL ENABLE);
  ALTER TABLE "NASRA"."BOOK" MODIFY ("BOOKID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUBLISHER
--------------------------------------------------------

  ALTER TABLE "NASRA"."PUBLISHER" ADD CONSTRAINT "PUBLISHER_PK" PRIMARY KEY ("PUBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."PUBLISHER" MODIFY ("PUBNAME" NOT NULL ENABLE);
  ALTER TABLE "NASRA"."PUBLISHER" MODIFY ("PUBID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "NASRA"."PAYMENT" ADD CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PRICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."PAYMENT" MODIFY ("PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERR
--------------------------------------------------------

  ALTER TABLE "NASRA"."ORDERR" ADD CONSTRAINT "ORDERR_PK" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."ORDERR" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "NASRA"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."EMPLOYEE" MODIFY ("EMPNAME" NOT NULL ENABLE);
  ALTER TABLE "NASRA"."EMPLOYEE" MODIFY ("EMPID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "NASRA"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."CUSTOMER" MODIFY ("CUSTNAME" NOT NULL ENABLE);
  ALTER TABLE "NASRA"."CUSTOMER" MODIFY ("CUSTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "NASRA"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."CATEGORY" MODIFY ("CATID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOOK_ORDER
--------------------------------------------------------

  ALTER TABLE "NASRA"."BOOK_ORDER" ADD CONSTRAINT "BOOK_ORDER_PK" PRIMARY KEY ("BOOKORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NASRA"."BOOK_ORDER" MODIFY ("BOOKORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "NASRA"."BOOK" ADD CONSTRAINT "BOOK_FK1" FOREIGN KEY ("AUTHID")
	  REFERENCES "NASRA"."AUTHOR" ("AUTHID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NASRA"."BOOK" ADD CONSTRAINT "BOOK_FK2" FOREIGN KEY ("PUBID")
	  REFERENCES "NASRA"."PUBLISHER" ("PUBID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "NASRA"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK1" FOREIGN KEY ("CUSTID")
	  REFERENCES "NASRA"."CUSTOMER" ("CUSTID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NASRA"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK2" FOREIGN KEY ("EMPID")
	  REFERENCES "NASRA"."EMPLOYEE" ("EMPID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERR
--------------------------------------------------------

  ALTER TABLE "NASRA"."ORDERR" ADD CONSTRAINT "ORDERR_FK1" FOREIGN KEY ("CUSTID")
	  REFERENCES "NASRA"."CUSTOMER" ("CUSTID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NASRA"."ORDERR" ADD CONSTRAINT "ORDERR_FK2" FOREIGN KEY ("EMPID")
	  REFERENCES "NASRA"."EMPLOYEE" ("EMPID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "NASRA"."CATEGORY" ADD CONSTRAINT "CATEGORY_FK1" FOREIGN KEY ("BOOKID")
	  REFERENCES "NASRA"."BOOK" ("BOOKID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK_ORDER
--------------------------------------------------------

  ALTER TABLE "NASRA"."BOOK_ORDER" ADD CONSTRAINT "BOOK_ORDER_FK1" FOREIGN KEY ("ORDERID")
	  REFERENCES "NASRA"."ORDERR" ("ORDERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NASRA"."BOOK_ORDER" ADD CONSTRAINT "BOOK_ORDER_FK2" FOREIGN KEY ("BOOKID")
	  REFERENCES "NASRA"."BOOK" ("BOOKID") ON DELETE CASCADE ENABLE;
