/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myframebooksotre;

import javax.swing.JOptionPane;

/**
 *
 * @author mustaf
 */
public class login1 extends javax.swing.JFrame {
 codes1 co= new codes1();
    /**
     * Creates new form login1
     */
    public login1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelTextIcon3 = new RSMaterialComponent.RSLabelTextIcon();
        username = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconOne1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("Login ");
        rSLabelTextIcon1.setFont(new java.awt.Font("Roboto Bold", 1, 48)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        jPanel1.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 70));

        rSLabelTextIcon2.setForeground(new java.awt.Color(153, 153, 153));
        rSLabelTextIcon2.setText("User Name");
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NATURE);
        jPanel1.add(rSLabelTextIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        rSLabelTextIcon3.setForeground(new java.awt.Color(153, 153, 153));
        rSLabelTextIcon3.setText("Password");
        rSLabelTextIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCK);
        jPanel1.add(rSLabelTextIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setPlaceholder("Enter your UserName");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 260, -1));

        rSButtonMaterialIconOne1.setBackground(new java.awt.Color(104, 87, 121));
        rSButtonMaterialIconOne1.setText("Login");
        rSButtonMaterialIconOne1.setBackgroundHover(new java.awt.Color(153, 153, 153));
        rSButtonMaterialIconOne1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rSButtonMaterialIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCK);
        rSButtonMaterialIconOne1.setPositionIcon(rojeru_san.efectos.ValoresEnum.POSITIONICON.RIGHT);
        rSButtonMaterialIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 220, 70));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 202, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne1ActionPerformed
        // TODO add your handling code here:
   String uname= username.getText();
        String pass= password.getText();

        if(uname.equals("bookstore")&&(pass.equals("123"))){
            Dashboard ds = new Dashboard();
            //jPanel1.add(db);
            ds.setVisible(true);
        }
        else
        {
           JOptionPane.showMessageDialog(null, "provide a valid username and password");
        username.setText("");
        password.setText("");
        }
    }//GEN-LAST:event_rSButtonMaterialIconOne1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon3;
    private RSMaterialComponent.RSTextFieldMaterial username;
    // End of variables declaration//GEN-END:variables
}
