/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myframebooksotre;

import javax.swing.JOptionPane;

/**
 *
 * @author mustaf
 */
public class Payment extends javax.swing.JInternalFrame {

  codes1 co= new codes1();
  String id="";
public void display(){
    co.viewTable("select * from PAYMENT", jTable1);
    
    
}
    public Payment() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt1 = new RSMaterialComponent.RSTextFieldMaterial();
        txt2 = new RSMaterialComponent.RSTextFieldMaterial();
        txt3 = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconOne2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne4 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSButtonMaterialIconOne5 = new RSMaterialComponent.RSButtonMaterialIconOne();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt1.setForeground(new java.awt.Color(153, 153, 153));
        txt1.setToolTipText("");
        txt1.setPlaceholder("Enter price");
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        txt2.setForeground(new java.awt.Color(153, 153, 153));
        txt2.setToolTipText("");
        txt2.setPlaceholder("Enter customer ID");
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        txt3.setForeground(new java.awt.Color(153, 153, 153));
        txt3.setToolTipText("");
        txt3.setPlaceholder("Enter Employee ID");
        jPanel2.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        rSButtonMaterialIconOne2.setBackground(new java.awt.Color(104, 87, 121));
        rSButtonMaterialIconOne2.setForeground(new java.awt.Color(0, 153, 153));
        rSButtonMaterialIconOne2.setText("Insert");
        rSButtonMaterialIconOne2.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 110, -1));

        rSButtonMaterialIconOne3.setBackground(new java.awt.Color(104, 87, 121));
        rSButtonMaterialIconOne3.setForeground(new java.awt.Color(0, 153, 153));
        rSButtonMaterialIconOne3.setText("Update");
        rSButtonMaterialIconOne3.setActionCommand("update");
        rSButtonMaterialIconOne3.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconOne3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 110, -1));

        rSButtonMaterialIconOne1.setBackground(new java.awt.Color(104, 87, 121));
        rSButtonMaterialIconOne1.setForeground(new java.awt.Color(0, 153, 153));
        rSButtonMaterialIconOne1.setText("Delete");
        rSButtonMaterialIconOne1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 110, -1));

        rSButtonMaterialIconOne4.setBackground(new java.awt.Color(104, 87, 121));
        rSButtonMaterialIconOne4.setForeground(new java.awt.Color(0, 153, 153));
        rSButtonMaterialIconOne4.setText("clear");
        rSButtonMaterialIconOne4.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconOne4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        rSButtonMaterialIconOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne4ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 110, -1));

        rSLabelTextIcon1.setBackground(new java.awt.Color(153, 153, 153));
        rSLabelTextIcon1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 153, 153)));
        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("Payment record");
        rSLabelTextIcon1.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PAYMENT);
        jPanel2.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 520, 90));

        rSButtonMaterialIconOne5.setBackground(new java.awt.Color(104, 87, 121));
        rSButtonMaterialIconOne5.setForeground(new java.awt.Color(0, 153, 153));
        rSButtonMaterialIconOne5.setText("Search");
        rSButtonMaterialIconOne5.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButtonMaterialIconOne5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonMaterialIconOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne5ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 110, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Price");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Employee ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 770));

        jTable1.setBackground(new java.awt.Color(0, 51, 102));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Price", "Customer ID", "Employee ID"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 540, 690));

        rSLabelTextIcon2.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 153, 153)));
        rSLabelTextIcon2.setForeground(new java.awt.Color(0, 0, 102));
        rSLabelTextIcon2.setText("Table gridview");
        rSLabelTextIcon2.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EVENT_NOTE);
        jPanel1.add(rSLabelTextIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 550, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne3ActionPerformed
        // TODO add your handling code here:
        String sql= "update PAYMENT set CUSTID='"+txt2.getText()+"',EMPID='"+txt3.getText()+"' where PRICE='"+txt1.getText()+"'";
        co.setSQL(sql);
        display();
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
     

    }//GEN-LAST:event_rSButtonMaterialIconOne3ActionPerformed

    private void rSButtonMaterialIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne2ActionPerformed
        // TODO add your handling code here:
        String sql= "insert into PAYMENT values('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"')";
        co.setSQL(sql);
        display();
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
       // txt4.setText("");

    }//GEN-LAST:event_rSButtonMaterialIconOne2ActionPerformed

    private void rSButtonMaterialIconOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne4ActionPerformed
        // TODO add your handling code here:
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
     //   txt4.setText("");
    }//GEN-LAST:event_rSButtonMaterialIconOne4ActionPerformed

    private void rSButtonMaterialIconOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne5ActionPerformed
        // TODO add your handling code here:
        String sql="select * from PAYMENT where PRICE='"+txt1.getText()+"' or CUSTID='"+txt2.getText()+"' or EMPID='"+txt3.getText()+"'";
        co.search(sql);
        try{
            if(co.rs.next()){
                id=co.rs.getString("PRICE");
                txt1.setText(co.rs.getString("PRICE"));
                txt2.setText(co.rs.getString("CUSTID"));
                txt3.setText(co.rs.getString("EMPID"));
              

            }
            else
            JOptionPane.showMessageDialog(null, "record not found");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());

        }
    }//GEN-LAST:event_rSButtonMaterialIconOne5ActionPerformed

    private void rSButtonMaterialIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne1ActionPerformed
        // TODO add your handling code here:
        String sql="delete from PAYMENT where PRICE='"+txt1.getText()+"' ";
        co.setSQL(sql);
        display();
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
       // txt4.setText("");

    }//GEN-LAST:event_rSButtonMaterialIconOne1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne3;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne4;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne5;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSTextFieldMaterial txt1;
    private RSMaterialComponent.RSTextFieldMaterial txt2;
    private RSMaterialComponent.RSTextFieldMaterial txt3;
    // End of variables declaration//GEN-END:variables
}
